Create close-jira-ticket.yml
fauna/faunadb-csharp pull request #142
Opened 2021-04-21 12:44 UTC by fireridlle

2021-04-21 13:23 UTC, parkhomenko approved these changes

2021-05-06 14:40 UTC, evbruno submitted a review, later dismissed

2021-07-26 21:30 UTC, macnealefauna requested changes

2021-07-26 21:30 UTC, macnealefauna commented on .github/workflows/close-jira-ticket.yml
> +        uses: atlassian/gajira-find-issue-key@master
s/master/main/

2021-07-26 21:30 UTC, macnealefauna commented on .github/workflows/close-jira-ticket.yml
> +        uses: atlassian/gajira-transition@master
s/master/main/

2022-02-11 01:35 UTC, cleve-fauna approved these changes

2022-02-11 01:35 UTC, merged