Oss 865 Implement new driver exceptions hierarchy
fauna/faunadb-csharp pull request #165
Opened 2021-08-18 12:52 UTC by shestakovg

### Overview
 Implemented new driver exceptions hierarchy
### Jira ticket
https://faunadb.atlassian.net/browse/OSS-865

2021-08-18 16:50 UTC, parkhomenko commented on FaunaDB.Client/Errors/FaunaException.cs
> +    public class CallError : FaunaException
To be consistent with other drivers, let's call it a `FunctionCallException`

2021-08-18 16:51 UTC, parkhomenko commented on FaunaDB.Client/Errors/FaunaException.cs
> +        public CallError(int httpStatusCode, string message, string[] position) : base(httpStatusCode, ExceptionCodes.CallError, message, position) { }
There is also an internal `cause` object that needs to be added here, check out a Java driver for this:https://github.com/fauna/faunadb-jvm/blob/OSS-864/faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java#L536

2021-08-18 16:53 UTC, parkhomenko commented on FaunaDB.Client/Errors/FaunaException.cs
> +        public ValidationFailed(int httpStatusCode, string message, string[] position) : base(httpStatusCode, ExceptionCodes.ValidationFailed, message, position) { }
There is an internal `failure` object that needs to be added here:
https://github.com/fauna/faunadb-jvm/blob/OSS-864/faunadb-java/src/main/java/com/faunadb/client/FaunaClient.java#L570

2021-08-18 16:53 UTC, parkhomenko commented on FaunaDB.Client/Errors/FaunaException.cs
> +    public class ValidationFailed : FaunaException
Let's be consistent with other drivers and add an `Exception` suffix to each class here, so this one, for example, will be named `ValidationFailedException`

2021-08-18 16:54 UTC, parkhomenko requested changes
Everything looks great!
I've left some comments. Also, check out the doc for exceptions you missed to test:
https://docs.google.com/spreadsheets/d/1j-ee0Ipp8MzSsXHiP7Z-gs0hv4-ejm6qfI-uETVfsvA/edit#gid=0

2021-08-18 23:44 UTC, freels requested changes

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionResolver.cs
> +        public static FaunaException[] Resolve(QueryErrorResponse responce, int httpStatusCode)
```suggestion
        public static FaunaException[] Resolve(QueryErrorResponse response, int httpStatusCode)
```

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionResolver.cs
> +                    case ExceptionCodes.InvaliRef:
```suggestion
                    case ExceptionCodes.InvalidRef:
```

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionResolver.cs
> +                string[] exceptionPositions = new string[error.Position.Count];
singular?
```suggestion
                string[] exceptionPosition = new string[error.Position.Count];
```

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionCode.cs
> +        public const string SchemaNotFound = "schema not found";
remove (and related exception class)

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionCode.cs
> +        public const string InvalidScope = "invalid scope";
remove (and related exception class)

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionCode.cs
> +        public const string InvalidObjectInContainer = "invalid object in container";
remove (and related exception class)

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionCode.cs
> +        public const string MoveDatabaseError = "move database error";
remove (and related exception class)

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Errors/ExceptionCode.cs
> +        public const string RecoveryFailed = "recovery failed";
remove (and related exception class)

2021-08-18 23:44 UTC, freels commented on FaunaDB.Client/Client/FaunaClient.cs
> +            throw ExceptionResolver.Resolve(response, statusCode).FirstOrDefault();
did we ever handle the case where the response body was not valid JSON? We need to handle that here, throwing the correct exception based on the HTTP status code as a fallback. See the Java driver for an example.

2021-09-23 14:24 UTC, parkhomenko approved these changes

2021-10-01 11:44 UTC, merged